84 implement posts api for course forums
ubclaunchpad/forum pull request #105
Opened 2024-11-24 01:44 UTC by bcw117

## Proposed Changes

- Addresses #84

2024-11-24 04:59 UTC, armintalaie requested changes
Awesome work @bcw117 - some tiny tweaks :)

2024-11-24 04:59 UTC, armintalaie commented on backend/routers/routes/posts.py
> +    user_id = "686fa92e-696d-4bf8-9b27-1dbc626fc5e9"
for the middleware - we can access the user now - check `auth.py`

2024-11-24 04:59 UTC, armintalaie commented on backend/main.py
> +app.include_router(post_router)
- Pull from `dev` and see how the `courses.py` is setting `documents` as its subpath

2024-11-24 04:59 UTC, armintalaie commented on backend/routers/routes/posts.py
> +
thoughts on moving this to the `models` folder - (i noticed we were adding a bunch of these classes)
https://github.com/ubclaunchpad/forum/tree/dev/backend/models

2024-11-25 04:21 UTC, armintalaie approved these changes
Good work. Thanks for adding proper status codes. 

- can u add response model for the endpoints (helps for FE folks and also throws an error on backend in response is not how it should be structured)
- add foreign ref to the posts table to connect to the user

2024-11-25 04:21 UTC, armintalaie commented on backend/models/post_models.py
> +    title: str
can we add field validator here? https://docs.pydantic.dev/latest/concepts/validators/#field-validators
i.e. "has to be at least 5 characters?"

2024-11-25 04:21 UTC, armintalaie commented on backend/models/post_models.py
> +    tags: list[str]
validator for this. all tags should be alphanumeric or have slash. Use gpt or something to make a regex for it. Basically 
`<word>/<word>` or `<word>` 

Bad:
- ""
- "assignments//1"
- "assignment??/"
- "_a"
- ..

2024-11-25 04:21 UTC, armintalaie commented on backend/routers/routes/posts.py
> +@post_router.post("")
for the endpoints make a response model:
`@document_router.post("", response_model=DocumentResponse)`

2024-11-25 04:21 UTC, armintalaie commented on backend/database/migrations/1731975568326.sql
> +  created_by uuid,
this should reference a user (add a foreign constraint) (on delete do nothing)

2024-11-25 08:38 UTC, bcw117 commented on backend/database/migrations/1731975568326.sql
> +  created_by uuid,
Also added foreign constraint _edit_by_ in post_edits

2024-11-25 08:40 UTC, merged